!!com.example.app.properties.PropertiesData
appiumProperties:
  platformName: android
  deviceName: device
  udid: emulator-5554
  app: E:/LEARN/QA Engineer/Alterra/Learn-Appium/sample-apk.apk
  automationName: UIAutomator2
  newCommandTimeout: 120
  autoGrantPermissions: true
